version: '3.2'

services:
  backend1:
      build: ./backend
      tty: true
      volumes:
        - './backend:/backend-dir'
      expose:
        - "3000"
  backend2:
      build: ./backend
      tty: true
      volumes:
        - './backend:/backend-dir'
      expose:
        - "3000"
  backend3:
      build: ./backend
      tty: true
      volumes:
        - './backend:/backend-dir'
      expose:
        - "3000"
  loadbalancer:
      build: ./load-balancer
      tty: true
      links:
          - backend1
          - backend2
          - backend3
      ports:
          - '8080:8080'
volumes:
  backend:

